# **ТЕМА 10. Декораторы и исключения**

Отчёт по теме #10 выполнил

Цыганков Денис Николаевич ПИЭ-21-2


| Задание | Лаб_раб | Сам_раб |
|----------|----------|----------|
| 1    | +   | +  |
| 2   | +   | +   |
| 3    | +   | +   |
| 4    | +   | +   |
| 5    | +   | +   |

знак "+" - задание выполнено; знак "-" - задание не выполнено;
Работу проверили:  к.э.н., доцент Панов М.А.


# Лабораторная работа №1 

Наверняка вы думаете, что декораторы – это какая-то бесполезная вещь, которая вам никогда не пригодится, но тут вдруг на паре по математике преподаватель просит всех посчитать число Фибоначчи для 100. Кто-то будет считать вручную (так точно не нужно), кто-то посчитает на калькуляторе, а кто-то подумает, что он самый крутой и напишет рекурсивную программу на Python и немного огорчится, потому что данная программа будет достаточно долго считаться, если ее просто так запускать.


```
from functools import lru_cache

@lru_cache(None)
def fibonacci(n):
    if n == 0:
        return 0
    elif n == 1:
        return 1
    return fibonacci(n - 1) + fibonacci(n - 2)

if __name__ == '__main__':
    print(fibonacci(100))
```

![Desktop Screenshot 2023 12 08 - 00 27 39 36](https://github.com/AngryPopuas/University/assets/121407501/5694c64d-1ec1-4df5-a77d-4e7d238da59d)

# Лабораторная работа №2

Илья пишет свой сайт и ему необходимо сделать минимальную проверку ввода данных пользователя при регистрации. Для этого он реализовал функцию, которая выводит данные пользователя на экран и решил, что будет проверять правильность введённых данных при помощи декоратора, но в этом ему потребовалась ваша помощь

```
def check(input_func):
    def output_func(*args):
        name, age = args[0], args[1]

        if age < 0 or age > 130:
            age = 'Недопустимый возраст'
        input_func(name,age)

    return output_func

@check
def personal_info(name,age):
    print(f"Name: {name} Age: {age}")

if __name__ == '__main__':
    personal_info('Владимир',38)
    personal_info('Александр',-5)
    personal_info('Петр',138,15,48,2)
```

![Desktop Screenshot 2023 12 08 - 00 32 27 94](https://github.com/AngryPopuas/University/assets/121407501/d8c43841-3c7e-4184-a735-af35df18c009)


# Лабораторная работа №3

Вам понравилась идея Ильи с сайтом, и вы решили дальше работать вместе с ним. Но вот в вашем проекте появилась проблема, кто-то пытается сломать вашу функцию с получением данных для сайта. Эта функция работает только с данными integer, а какой-то недохакер пытается все сломать и вместо нужного типа данных отправляет string.


```
def data(*args):
    try:
        for i in range(len(*args)):
            try:
                result = (args[0][i] * 15) // 10
                print(result)
            except Exception as ex:
                print(ex)
    except Exception as ex:
        print(ex)
    finally:
        print('Вся информация обработана')

if __name__ == '__main__':
    data([1,15,'Hello','i','try','to','crash','your','site',38,45])
```

![Desktop Screenshot 2023 12 08 - 00 39 56 28](https://github.com/AngryPopuas/University/assets/121407501/82f6194e-9396-4a80-9b1a-f94afcf1e96d)


# Лабораторная работа №4

После запуска сайта вы поняли, что вам необходимо добавить логгер, для отслеживания его работы. Готовыми вариантами вы не захотели пользоваться, и поэтому решили создать очень простую пародию. Для этого создали две функции: __init__() (вызывается при создании класса декоратора в программе) и __call__() (вызывается при вызове декоратора). Создайте необходимый вам декоратор. Выведите все логи в консоль

```
class NegativeValueException(Exception):
    pass

def check_name(name):
    if len(name > 10):
        raise NegativeValueException('Длинна более 10 символов')
    else:
        print('Успешная регистрация')

if __name__ == '__main__':
    name = '1234567810'
    check_name(name)
```

![Desktop Screenshot 2023 12 08 - 00 42 46 57](https://github.com/AngryPopuas/University/assets/121407501/a9ab6cdc-c745-436a-84bd-232362fb77fd)

# Лабораторная работа №5

После запуска сайта вы поняли, что вам необходимо добавить логгер, для отслеживания его работы. Готовыми вариантами вы не захотели пользоваться, и поэтому решили создать очень простую пародию. Для этого создали две функции: __init__() (вызывается при создании класса декоратора в программе) и __call__() (вызывается при вызове декоратора). Создайте необходимый вам декоратор. Выведите все логи в консоль

```
class SiteChecker:
    def __init__(self,func):
        print('> Класс SiteChecker метод __init__ успешный запуск')
        self.func = func

    def __call__(self):
        print('Ю Проверка перед запуском', self.func.__name__)
        self.func()
        print('> Проверка безопасного выключения')

@SiteChecker
def site():
    print('Усердная работа сайта')

if __name__ == '__main__':
    print('>> Сайт запущен')
    site()
    print('>> Сайт выключен')
```

![Desktop Screenshot 2023 12 08 - 00 48 11 23](https://github.com/AngryPopuas/University/assets/121407501/cccd9362-10aa-49de-b1d8-a7ec0a4d4a0f)

# Самостоятельная работа №1

Вовочка решил заняться спортивным программированием на python, но для этого он должен знать за какое время выполняется его программа. Он решил, что для этого ему идеально подойдет декоратор для функции, который будет выяснять за какое время выполняется та или иная функция. Помогите Вовочке в его начинаниях и напишите такой декоратор

```

import time
def fibonacci(function):
    def wrapped(*args):
        fib1 = fib2 = 1

        start_time = time.perf_counter_ns()
        for i in range(2,200):
            fib1, fib2 = fib2, fib1 + fib2
            print(fib2, end='')

        res = function(*args)
        print(time.perf_counter_ns() - start_time)
        return res
    return wrapped

@fibonacci
def func(first, second):
    return bin(int(first, 2) + int(second, 2))


print(func("111", "0000"))
```

![Desktop Screenshot 2023 12 08 - 01 31 35 06](https://github.com/AngryPopuas/University/assets/121407501/80074cbb-7598-4da3-b5b7-24154d19a6f7)


# Вывод:

```@time_of_function``` - декоратор, который подсчитывает сколько выполняется функция 

```for i in range(2,200): ``` - цикл for, который считает число фибоначи, до 200 значения

```start_time = time.perf_counter_ns()``` - старт таймера

```print(time.perf_counter_ns() - start_time)``` - конец таймера


# Самостоятельная работа №2

Посмотрев на Вовочку, вы также загорелись идеей спортивного программирования, начав тренировки вы узнали, что для решения некоторых задач необходимо считывать данные из файлов. Но через некоторое время вы столкнулись с проблемой что файлы бывают пустыми, и вы не получаете вводные данные для решения задачи. После этого вы решили не просто считывать данные из файла, а всю конструкцию оборачивать в исключения, чтобы избежать такой

```
class NegativeValueException(Exception):
    pass

def check_name():
    f = open('text.txt', 'r')
    if f.read() == '':
        raise NegativeValueException('Файл пустой')
    else:
        print(f)

if __name__ == '__main__':
    check_name()
```

![Desktop Screenshot 2023 12 08 - 01 38 47 30](https://github.com/AngryPopuas/University/assets/121407501/26433ba3-cdb9-464f-af5c-84bf7ae87409)

# Вывод:

```f = open('text.txt', 'r')``` внутри функции, открывает файл. 

```if f.read() == '':``` вызывает метод read без аргументов и проверяет является ли результат пустой строкой. 

В случае если да, мы получаем исключение



# Самостоятельная работа №3

Напишите функцию, которая будет складывать 2 и введенное пользователем число, но если пользователь введет строку или другой неподходящий тип данных, то в консоль выведется ошибка “Неподходящий тип данных. Ожидалось число.”. Реализовать функционал программы необходимо через try/except и подобрать правильный тип исключения. Создавать собственное исключение нельзя. Проведите несколько тестов, в которых исключение вызывается и нет. Результатом выполнения задачи будет листинг кода и получившийся вывод в консоль


```
def data(args):
    try:
        result = args + 2
        print(result)
    except Exception as ex:
        print('Неподходящий тип данных. Ожидалось число')

if __name__ == '__main__':
    data(20)
```

![Desktop Screenshot 2023 12 08 - 01 50 47 78](https://github.com/AngryPopuas/University/assets/121407501/5b6f5796-4e33-430c-bb41-5ca1209bce76)

# Вывод:

Данная функция ```def data(args): ``` принимает аргументом число, прибавляет к нему 2. 

Но, также, выбрасывает исключение если аргумент не является числом: ```     except Exception as ex: ```

Выводя в консоль: ```print('Неподходящий тип данных. Ожидалось число') ```

# Самостоятельная работа №4

Создайте собственный декоратор, который будет использоваться для двух любых вами придуманных функций. Декораторы, которые использовались ранее в работе нельзя воссоздавать. Результатом выполнения задачи будет: класс декоратора, две как-то связанными с ним функциями, скриншот консоли с выполненной программой и подробные комментарии, которые будут описывать работу вашего кода

```
def a_decorator_passing_arguments(function_to_decorate):
    def a_wrapper_accepting_arguments(arg1, arg2):
        print
        "Смотри, что я получил:", arg1, arg2
        function_to_decorate(arg1, arg2)

    return a_wrapper_accepting_arguments

@a_decorator_passing_arguments
def print_full_name(first_name, last_name):
    print
    "Меня зовут", first_name, last_name


print_full_name("Питер", "Венкман")
```

![Desktop Screenshot 2023 12 08 - 01 52 46 24](https://github.com/AngryPopuas/University/assets/121407501/b0dbfe8b-6966-467a-b0fd-5d9c82a0637e)

# Вывод:

Мы вызываем функцию, которую возвращает декоратор,

Мы вызываем её "обёртку", передаём ей аргументы и уже в свою очередь она передаёт их декорируемой функции

```print_full_name("Питер", "Венкман") ```

Смотри, что я получил: Питер Венкман

Меня зовут Питер Венкман

# Самостоятельная работа №5

Создайте собственное исключение, которое будет использоваться в двух любых фрагментах кода. Исключения, которые использовались ранее в работе нельзя воссоздавать. Результатом выполнения задачи будет: класс исключения, код к котором в двух местах используется это исключение, скриншот консоли с выполненной программой и подробные комментарии, которые будут описывать работу вашего кода

```
class MyCustomException(Exception):
    def __init__(self, message, extra_info):
        super().__init__(message)
        self.extra_info = extra_info

def divide_numbers(a, b):
    if b == 0:
        raise MyCustomException("Деление на ноль невозможно", {"a": a, "b": b})
    return a / b

try:
    result = divide_numbers(10, 0)
except MyCustomException as e:
    print(f"Сообщение об ошибке: {e}")
    print(f"Дополнительная информация: {e.extra_info}")
```

![Desktop Screenshot 2023 12 08 - 01 55 48 57](https://github.com/AngryPopuas/University/assets/121407501/d872d71c-40f1-4504-9e67-c0f43a4b597b)

# Вывод:

В данном коде, определен новый класс, который наследует от базового класса Exception или другого подходящего класса исключения. MyCustomException:

Он проверяет является ли делитель нулю. ``` if b == 0 ```

И если это так выбрасывает исключение ``` raise MyCustomException("Деление на ноль невозможно", {"a": a, "b": b}) ```

